0
1
raised ValueError()
ret was: None
ValueError from just-started gen
